labels:
  - name: bug
    color: ee0701
  - name: contribution welcome
    color: 0e8a16
  - name: discussion
    color: 4935ad
  - name: docs
    color: 8be281
  - name: enhancement
    color: a2eeef
  - name: good first issue
    color: 7057ff
  - name: help wanted
    color: 008672
  - name: question
    color: d876e3
  - name: wontfix
    color: ffffff
  - name: WIP
    color: ffffff
  - name: need repro
    color: c9581c
  - name: feature request
    color: fbca04
